export const ShoppingCart = () => {
    return <aside>
        <div className="widget">
            <h3 className="titulo">Articulos destacados</h3>
            <ul>
                <li><a href="#"> Articulo destacado de SpringBoot</a></li>
                <li><a href="#"> Articulo destacado de Angular</a></li>
                <li><a href="#"> Articulo destacado de Microservicios</a></li>
                <li><a href="#"> Articulo destacado de AWS</a></li>
                <li><a href="#"> Articulo destacado de Google Cloud</a></li>

            </ul>
        </div>

        <div className="widget">
            <h3 className="titulo">Información</h3>
            <p>
                By default, the data.sql script executes before Hibernate initialization.
                This aligns the script-based initialization with other database migration tools such as Flyway
                and Liquibase.
                As we're recreating the schema generated by Hibernate each time, we need to set an additional
                property
            </p>
        </div>
    </aside>
}