import './AppLibrary.css'
import {Navigation} from "./components/navigation/navigation.jsx";

function AppLibrary() {

  const myItems = [
      { name: 'Tiendas fisicas', href:"", className: "item-text" },
      { name: 'Eventos',  href:"", className: "item-text" },
      { name: 'Ayuda',  href:"", className: "item-text" },
      { name: '',  href:"", className: "item item-shopping-cart" },
      { name: '',  href:"", className: "item item-user" }
  ];

  return (
      <>
          <div className="container">
                <Navigation items={myItems}/>

              <section className="main">
                  <div className="imagen">
                      <img src="src/images/wallpaper.jpg" alt="#"/>
                  </div>
                  <section className="post">
                      <article>
                          <h2>Titulo del articulo</h2>
                          <p>
                              By default, the data.sql script executes before Hibernate initialization.
                              This aligns the script-based initialization with other database migration tools such as
                              Flyway and Liquibase.
                              As we're recreating the schema generated by Hibernate each time, we need to set an
                              additional property
                          </p>
                          <p>
                              By default, the data.sql script executes before Hibernate initialization.
                              This aligns the script-based initialization with other database migration tools such as
                              Flyway and Liquibase.
                              As we're recreating the schema generated by Hibernate each time, we need to set an
                              additional property
                          </p>
                      </article>
                  </section>
              </section>
              <aside>
                  <div className="widget">
                      <h3 className="titulo">Articulos destacados</h3>
                      <ul>
                          <li><a href="#"> Articulo destacado de SpringBoot</a></li>
                          <li><a href="#"> Articulo destacado de Angular</a></li>
                          <li><a href="#"> Articulo destacado de Microservicios</a></li>
                          <li><a href="#"> Articulo destacado de AWS</a></li>
                          <li><a href="#"> Articulo destacado de Google Cloud</a></li>

                      </ul>
                  </div>

                  <div className="widget">
                      <h3 className="titulo">Información</h3>
                      <p>
                          By default, the data.sql script executes before Hibernate initialization.
                          This aligns the script-based initialization with other database migration tools such as Flyway
                          and Liquibase.
                          As we're recreating the schema generated by Hibernate each time, we need to set an additional
                          property
                      </p>
                  </div>
              </aside>

              <footer>
                  <p>Jhon Roberth Fernandez - Derechos reservados</p>
                  <ul>
                      <li><a href="#">Facebook</a></li>
                      <li><a href="#">LikedIn</a></li>
                      <li><a href="#">Twitter</a></li>
                  </ul>
              </footer>
          </div>

      </>
  )
}

export default AppLibrary
